<?php
/**
 * TL_ROOT/system/modules/xtmembers_outlook/languages/de/tl_member.php 
 * 
 * TYPOlight extension: xtmembers_outlook 1.0.0 beta2 
 * Deutsch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_member']['outlook_field']['0'] = "Outlook-Feld";
$GLOBALS['TL_LANG']['tl_member']['outlook_field']['1'] = "Name des Export-Feldes in den Microsoft Outlook Kontaktdaten";
$GLOBALS['TL_LANG']['tl_member']['member_field']['0'] = "Mitgliedsfeld";
$GLOBALS['TL_LANG']['tl_member']['member_field']['1'] = "Name des TYPOlight Mitgliedsfeldes";
$GLOBALS['TL_LANG']['tl_member']['start_export'] = "Exportieren";
$GLOBALS['TL_LANG']['tl_member']['start_import'] = "Importieren";
$GLOBALS['TL_LANG']['tl_member']['info_export'] = "Bitte weisen Sie den TYPOlight Mitgliedsfeldern die zugehörigen Outlook Kontaktfelder zu. Ihre Auswahl wird gespeichert und kann beim nächsten Mal wiederverwendet werden.";
$GLOBALS['TL_LANG']['tl_member']['outlooksource']['0'] = "Quelldatei";
$GLOBALS['TL_LANG']['tl_member']['outlooksource']['1'] = "Bitte wählen Sie eine Outlook Export-Datei im .csv Format aus dem Datenverzeichnis aus.";
$GLOBALS['TL_LANG']['tl_member']['outlook_import_groups']['0'] = "Mitgliedergruppen";
$GLOBALS['TL_LANG']['tl_member']['outlook_import_groups']['1'] = "Bitte wählen Sie die Mitgliedergruppen aus, die den importierten Mitgliedern zugewiesen werden sollen.";
$GLOBALS['TL_LANG']['tl_member']['outlook_import_newsletter']['0'] = "Newsletter";
$GLOBALS['TL_LANG']['tl_member']['outlook_import_newsletter']['1'] = "Bitte wählen Sie die Newsletter aus, die den importierten Mitgliedern zugewiesen werden sollen.";
 
?>
